### PR TITLE
ENG-501: allow array of PublicKey

### PR DESCRIPTION
**Pull request by timmyjose**
Changes:
 - updated `polybase/client` version in `package.json`.
 - updated `polybase/polylang` version in `package.json`.
 - checking in `yarn.lock`.

### CODE REVIEW

**Comment by timmyjose** [comment]
This is the final PR for functionality complete of ENG-501: Allow array of PublicKey. Post this, only version changes will be needed as packages move from `beta`.

**Comment by calummoore** [comment]
Thanks, seems like there is an issue with the polylang parser. The following is not returning undefined, in `CollectionDetailData`.

```
import { parse, Program } from '@polybase/polylang'
parse(meta?.data?.code, collectionId).then(([ast]) => setAst(ast))
```

Going to investigate.

**Comment by timmyjose** [comment]
@calummoore Ah, okay. Please let me know if I can help out in any way!

**Comment by calummoore** [comment]
Fyi, nothing to do with your work. 👍

**Comment by calummoore** [comment]
Once this completes, you should be able to update explorer: https://github.com/polybase/polybase-ts/actions/runs/5032528973

**Comment by timmyjose** [comment]
> Fyi, nothing to do with your work. 👍

That's nice to hear, but it's a collective effort (and responsibility) all the same! 🙂

**Comment by timmyjose** [comment]
> Once this completes, you should be able to update explorer dependencies again: https://github.com/polybase/polybase-ts/actions/runs/5032528973

Okay, sounds good. Will do! 👍

**Comment by timmyjose** [comment]
Updated `polybase/client` dependency to `0.5.1-beta.367`, and tested.

**Comment by timmyjose** [comment]
Updated `polybase/polylang` to `0.4.12-beta.105`.

**Comment by calummoore** [comment]
I actually think its fine for now, but ordinarily we should also update the @polybase/react whenever @polybase/client is updated.

**Comment by timmyjose** [comment]
> I actually think its fine for now, but ordinarily we should also update the @polybase/react whenever @polybase/client is updated.

Okay, I'll keep that in mind. Thanks for the note!

**Pull request merged**
